import { StyleSheet } from 'react-native';

export const dashboardStyles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    marginBottom: 8,
  },
  greetingRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  greetingText: { fontSize: 24, fontWeight: '900', letterSpacing: -0.8 },
  streakBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
  streakText: { fontSize: 14, fontWeight: '800' },
  headerSubtitle: { fontSize: 14, fontWeight: '500', marginTop: 2 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  profileButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(150,150,150,0.1)',
  },
  avatarText: { fontSize: 16, fontWeight: '800' },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 150, paddingTop: 10 },
  motivationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 18,
    borderRadius: 24,
    marginBottom: 20,
    gap: 14,
  },
  iconCircle: { width: 36, height: 36, borderRadius: 18, justifyContent: 'center', alignItems: 'center' },
  insightText: { flex: 1, fontSize: 15, fontWeight: '700', lineHeight: 22 },
  card: {
    padding: 20,
    borderRadius: 28,
    marginBottom: 16,
    elevation: 2,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  cardLabel: { fontSize: 11, fontWeight: '900', letterSpacing: 1.2, marginBottom: 18 },
  statsGrid: { flexDirection: 'row', justifyContent: 'space-around' },
  statItem: { alignItems: 'center' },
  statValue: { fontSize: 22, fontWeight: '900', marginTop: 6 },
  statSubLabel: { fontSize: 10, fontWeight: '800', opacity: 0.6 },
  chartContainer: { marginLeft: -20, marginTop: 10 },
  runItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomColor: 'rgba(150,150,150,0.1)',
  },
  runDate: { fontSize: 16, fontWeight: '700' },
  runDetails: { fontSize: 13, fontWeight: '600', marginTop: 2 },
  fabContainer: { position: 'absolute', bottom: 40, width: '100%', alignItems: 'center' },
  fab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 32,
    paddingVertical: 20,
    borderRadius: 40,
    gap: 12,
    elevation: 12,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
  },
  fabText: { fontSize: 16, fontWeight: '900', letterSpacing: 1.5 },
});
